### ISSUE TITLE
Dockerize?

### ISSUE THREAD

**Issue by roelbroersma** [psi-4ward/s7client#10]
It would be great if s7-client can be run on i.e. a Synology NAS,  on Docker.

For this, we would need to include a DOCKERFILE  and post it to the public Docker Registry.

**Comment by anthrogan** [comment]
But you can put s7client in a image/container if you make your own dockerfile? It's just set of functions that make working with node-snap7 easier tbh, it's not really a standalone library.

**Comment by roelbroersma** [comment]
Yes,  probably a Dockerfile with Node in it,  which downloads the latest functions

**Comment by roelbroersma** [comment]
Then that would be  a  "s7client" docker container,  ready to start with

**Comment by psi-4ward** [comment]
This is a library and it makes no sense to dockerize it cause you need at least some kind of software which exposes the functionality as a service.

**Comment by roelbroersma** [comment]
Well,.. the ultimate idea would be to have a Docker container which you just load on you Synology NAS....  which is a S7Client REST interface.

So needed is:
- Dockerize
- Rest framework


Then you can easily set connection parameters in  DOCKER ENVIRONMENT VARS,   and it's a very easy   S7Client  REST Gateway to connect your domoticz,.. IFTTT or other things..

**Comment by roelbroersma** [comment]
I was thinking,  when you create a docker file,  i will create the rest interface.    But that's in fact just loading a REST framework.


But if we could do it al in one project..  that's even better,.. and it wouldn't be that much more source..    1 file for the Docker container (dockerfile)  and a few lines extra code for the rest interface.
