### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by anthrogan** [psi-4ward/s7client#3]
I'm polling a PLC via setInterval once connected and passing data over socketio to a vue application.

Is there a more appropriate method to polling the PLC? Or is this the best way for "live" responses for a web front end?

**Comment by psi-4ward** [comment]
This is the way to go for now, see https://github.com/mathiask88/node-snap7/issues/21

I use the same approach in my (feathers) backend which polls the PLC DBs and emits socket events whenever a value changes

**Comment by anthrogan** [comment]
Ok bud, I'll carry on thank you!

**Comment by anthrogan** [comment]
I'll add a polling example to documentation when I get a few spare minutes if you like?

**Comment by psi-4ward** [comment]
of course please !
